name: nordeacsv-actions
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cmd
        working-directory: test_nordeacsv
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
      - name: Test with pytest
        run: |
          pytest
